---
name_tag: GIN+GPSE
out_dir: results
metric_best: accuracy
wandb:
  use: false
  project: GPSE-TRI
dataset:
  format: SyntheticWL
  name: cc0
  task: graph
  task_type: regression
  transductive: false
  node_encoder: true
  node_encoder_name: GPSE
posenc_GPSE:
  enable: true
  rand_type: NormalSE
  model_dir: pretrained_models/gpse_molpcba.pt
  dim_pe: 64
  model: Linear
  use_repr: true
  repr_type: no_post_mp
  model: Linear
  virtual_node: true
  input_dropout_be: 0.0
  input_dropout_ae: 0.0
  raw_norm_type: BatchNorm
  gnn_cfg:
    head: inductive_hybrid_multi
    layers_pre_mp: 1
    layers_mp: 20
    layers_post_mp: 2
    dim_inner: 512
    layer_type: resgatedgcnconv
    multi_head_dim_inner: 32  # use dim_inner if None
    stage_type: skipsum
    batchnorm: true
    act: relu
    dropout: 0.2
    agg: mean
    normalize_adj: false
train:
  mode: custom
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
model:
  type: gnn
  loss_fun: l1
  edge_decoding: dot
gnn:
  layers_pre_mp: 0
  layers_mp: 5
  layers_post_mp: 1
  dim_inner: 128
  layer_type: ginconv
  stage_type: skipsum
  batchnorm: true
  act: relu
  dropout: 0.0
  agg: add
  normalize_adj: false
optim:
  optimizer: adam
  base_lr: 0.002
  max_epoch: 200
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 20
  min_lr: 1e-5
